pipeline {
    agent any

    environment {
        IMAGE_NAME = "student-feedback-app"
        CONTAINER_NAME = "student-feedback-container"
    }

    stages {
        stage('Clone Source') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Test') {
            steps {
                sh 'docker images | grep $IMAGE_NAME'
            }
        }

        stage('Deploy with Ansible') {
            steps {
                sh 'ansible-playbook -i santhosh/ansible/inventory santhosh/ansible/deploy.yml'
            }
        }
    }
}
