---
- name: Deploy Student Feedback App
  hosts: local
  become: yes

  vars:
    image_name: student-feedback-app
    container_name: student-feedback-container

  tasks:
    - name: Stop old container if running
      shell: docker stop {{ container_name }} || true

    - name: Remove old container if exists
      shell: docker rm {{ container_name }} || true

    - name: Run new container
      shell: docker run -d --name {{ container_name }} -p 5000:5000 {{ image_name }}